# Jekyll Configuration for Static Pages

title: IBM FHIR Server
description: >- 
  The IBM FHIR Server is a modular Java implementation of version 4 
  of the <a href="https://www.hl7.org/fhir/r4/http.html">HL7 FHIR specification</a> with 
  a focus on performance and configurability.
baseurl: ""
url: "https://ibm.github.io/fhir" 

# Build settings
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
  - jekyll-redirect-from

source: . 
destination: _site
show_drafts: false
future: false

markdown: kramdown

paginate: 5
paginate_path: "blog/:num"

# Remote Theme - https://github.blog/2017-11-29-use-any-theme-with-github-pages/
theme: jekyll-theme-slate

relative_links:
  enabled:     true
  collections: false

# Remove the Default files 
optional_front_matter:
  remove_originals: true  

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false  

# Prefer to use GitHub flavored markdown - https://github.github.com/gfm/
markdown: GFM 

include:
  - CONTRIBUTING.md
  - README.md  
  - _posts/index.md

gems: 
  - jekyll-redirect-from
  - jekyll-sitemap  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
