name: Integration

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/site.yml'

jobs:
  build-tools:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ 'openjdk8', 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build tools
      run: mvn -B install --file fhir-tools -Dmaven.wagon.http.retryHandler.count=3
    - name: Build samples
      run: mvn -B install --file fhir-examples -Dmaven.wagon.http.retryHandler.count=3
    - name: Build parent without tests
      run: mvn -B install --file fhir-parent -DskipTests -P integration -Dmaven.wagon.http.retryHandler.count=3
    - name: Build sample generator
      run: mvn -B package --file fhir-examples-generator -Dmaven.wagon.http.retryHandler.count=3
    - name: Build benchmark
      run: mvn -B package --file fhir-benchmark -Dmaven.wagon.http.retryHandler.count=3
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ 'openjdk8', 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Fetch target branch
      env:
        BASE: ${{ github['base_ref'] }}
      run: git fetch --no-tags --prune --depth=1 origin +refs/heads/${BASE}:refs/remotes/origin/${BASE}
    - name: Build samples
      run: mvn -B install --file fhir-examples --no-transfer-progress
    - name: Build parent with tests
      env:
        BASE: origin/${{ github['base_ref'] }}
      run: |
        mvn -version
        model_paths=(
          fhir-model
          fhir-examples
        )
        validation_paths=(
          fhir-validation
          fhir-profile/src/main
          fhir-term/src/main
          fhir-path/src/main
          fhir-model/src/main
          fhir-examples
        )
        search_paths=(
          fhir-search
          fhir-examples
        )
        jdbc_paths=(
          fhir-persistence-jdbc
          fhir-search/src/main
          fhir-persistence/src/main
          fhir-persistence-schema/src/main
          fhir-examples
        )
        PROFILES_ARR=(integration)

        if [ -n "$(git --no-pager diff --name-only ${BASE} ${GITHUB_SHA} -- ${model_paths[@]})" ]; then
          echo "Changes affect fhir-model, running ALL"
          PROFILES_ARR+=(model-all-tests)
        else
          echo "No changes affect fhir-model, running MINIMAL"
        fi
        if [ -n "$(git --no-pager diff --name-only ${BASE} ${GITHUB_SHA} -- ${validation_paths[@]})" ]; then
          echo "Changes affect fhir-validation, running ALL"
          PROFILES_ARR+=(validation-all-tests)
        else
          echo "No changes affect fhir-validation, running MINIMAL"
        fi
        if [ -n "$(git --no-pager diff --name-only ${BASE} ${GITHUB_SHA} -- ${search_paths[@]})" ]; then
          echo "Changes affect fhir-search, running ALL"
          PROFILES_ARR+=(search-all-tests)
        else
          echo "No changes affect fhir-search, running MINIMAL"
        fi
        if [ -n "$(git --no-pager diff --name-only ${BASE} ${GITHUB_SHA} -- ${jdbc_paths[@]})" ]; then
          echo "Changes affect fhir-persistence-jdbc, running ALL"
          PROFILES_ARR+=(jdbc-all-tests)
        else
          echo "No changes affect fhir-persistence-jdbc, running MINIMAL"
        fi

        # Convert the PROFILES_ARR array to a comma-delimited string
        PROFILES=$(IFS=, ; echo "${PROFILES_ARR[*]}")
        echo "Using profiles ${PROFILES}"
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline -f fhir-parent -DexcludeReactor=true
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -f fhir-parent -DexcludeReactor=true
        mvn -B -T2C package --file fhir-parent -P "${PROFILES}" --no-transfer-progress -Dmaven.wagon.httpconnectionManager.ttlSeconds=240 -Dmaven.wagon.http.retryHandler.count=3
  e2e-tests:
    runs-on: ubuntu-16.04
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ 'openjdk8', 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      run: mvn -B install --file fhir-examples --no-transfer-progress
    - name: Build parent without tests
      # As the e2e tests are the fastest, opting to put javadoc:javadoc in fhir-parent
      # The profile avoids UML diagram creation
      run: |
        JAVADOC_GOAL=""
        if [ "${{ matrix.java }}" != "openjdk8" ]
        then
          export JAVA_HOME=/opt/hostedtoolcache/AdoptOpenJDK/1.0.0-releases-${{ matrix.java }}-hotspot-normal-latest/x64/
          JAVADOC_GOAL=" -Pvalidate-javadoc javadoc:javadoc "
        fi
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline -f fhir-parent -DexcludeReactor=true
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -f fhir-parent -DexcludeReactor=true
        mvn -B ${JAVADOC_GOAL} install --file fhir-parent -DskipTests -P integration --no-transfer-progress -Dmaven.wagon.httpconnectionManager.ttlSeconds=240 -Dmaven.wagon.http.retryHandler.count=3
    - name: free disk space
      run: |
        # create and remove a 200 MB file to make sure we have the room needed later
        dd if=/dev/urandom oflag=direct of=balloon.dat bs=1024k count=200
        rm -f balloon.dat
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: Server Integration Tests
      env:
        # debian-based linux uses C.UTF-8 by default and Derby doesn't like that
        LC_ALL: en_US.UTF-8
      run: |
        export WORKSPACE=${GITHUB_WORKSPACE}
        build/pre-integration-test.sh
        env
        mvn -B test -DskipTests=false -f fhir-server-test --no-transfer-progress -Dmaven.wagon.httpconnectionManager.ttlSeconds=240 -Dmaven.wagon.http.retryHandler.count=3
        build/post-integration-test.sh
    - name: Gather error logs
      if: failure()
      run: |
        it_results=SIT/integration-test-results
        rm -fr ${it_results} 2>/dev/null
        mkdir -p ${it_results}/server-logs
        mkdir -p ${it_results}/fhir-server-test
        echo "Gathering post-test server logs..."
        cp -pr SIT/wlp/usr/servers/fhir-server/logs ${it_results}/server-logs
        echo "Gathering integration test output"
        cp -pr ${GITHUB_WORKSPACE}/fhir-server-test/target/surefire-reports/* ${it_results}/fhir-server-test || true
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: integration-test-results-${{ matrix.java }}
        path: SIT/integration-test-results
  e2e-windows:
    runs-on: windows-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      shell: powershell
      run: mvn -B install --file fhir-examples/pom.xml --no-transfer-progress
    - name: Build parent without tests
      shell: powershell
      run: mvn -B install --file fhir-parent/pom.xml -DskipTests --no-transfer-progress
    - name: Server Integration Tests
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"
        & build/pre-integration-test.ps1
        & build/tests.ps1
        & build/post-integration-test.ps1
    - name: Gather error logs
      shell: powershell
      if: failure()
      run: |
        Write-Host 'Clean up existing integration test results'
        $it_results='SIT/integration-test-results'
        If (Test-Path -Path $it_results) {
          Remove-Item -path $it_results -Recurse -Force
        }

        Write-Host 'Create destinations for the files/folders'
        $DST_SL='server-logs'
        $DST_ST='fhir-server-test'
        New-Item -Path $it_results -Name $DST_SL -ItemType 'directory' -Force
        New-Item -Path $it_results -Name $DST_ST -ItemType 'directory' -Force

        Write-Host 'Gathering post-test server logs'
        $SRC_ST='SIT/wlp/usr/servers/fhir-server/logs'
        $DST_SL_F=$it_results + '/' + $DST_SL
        Copy-Item -Path $SRC_ST -Destination $DST_SL_F -Recurse -Force

        Write-Host 'Gathering integration test output'
        $SRC_ST='./fhir-server-test/target/surefire-reports'
        $DST_ST_F=$it_results + '/' + $DST_ST
        Copy-Item -Path $SRC_ST -Destination $DST_ST_F -Recurse -Force
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: integration-test-results-windows-${{ matrix.java }}
        path: SIT/integration-test-results
  e2e-db2-with-bulkdata:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ 'openjdk11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      run: mvn -B install --file fhir-examples --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
    - name: Build parent without tests
      run: |
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline -f fhir-parent -DexcludeReactor=true
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -f fhir-parent -DexcludeReactor=true
        mvn -B install --file fhir-parent -DskipTests -P integration --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
        mvn -B dockerfile:build -f fhir-install --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
    - name: free disk space
      run: |
        # create and remove a 200 MB file to make sure we have the room needed later
        dd if=/dev/urandom oflag=direct of=balloon.dat bs=1024k count=200
        rm -f balloon.dat
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: Server Integration Tests
      run: |
        export WORKSPACE=${GITHUB_WORKSPACE}
        build/pre-integration-test-docker.sh
        mvn -B test -DskipTests=false -f fhir-server-test --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
        build/post-integration-test-docker.sh
    - name: Gather error logs
      if: failure()
      run: |
        it_results=integration-test-results
        rm -fr ${it_results} 2>/dev/null
        mkdir -p ${it_results}/server-logs
        mkdir -p ${it_results}/fhir-server-test
        containerId=$(docker ps -a | grep fhir | cut -d ' ' -f 1)
        if [[ -z "${containerId}" ]]; then
            echo "Warning: Could not find fhir container!!!"
            bash build/docker/docker-cleanup.sh
        else
            echo "fhir container id: $containerId"

            # Grab the container's console log
            docker logs $containerId  >& ${it_results}/docker-console.txt

            echo "Gathering post-test server logs from docker container: $containerId"
            docker cp -L $containerId:/logs ${it_results}/server-logs
        fi
        echo "Gathering integration test output"
        cp -pr ${GITHUB_WORKSPACE}/fhir-server-test/target/surefire-reports/* ${it_results}/fhir-server-test || true
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: integration-test-results-db2-${{ matrix.java }}
        path: integration-test-results
  db2-migration:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ 'openjdk8' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: joschi/setup-jdk@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build samples
      run: mvn -B install --file fhir-examples --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
    - name: Build parent without tests
      run: |
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline -f fhir-parent -DexcludeReactor=true
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -f fhir-parent -DexcludeReactor=true
        mvn -B install --file fhir-parent -DskipTests -P integration --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
        mvn -B dockerfile:build -f fhir-install --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
    - name: free disk space
      run: |
        # create and remove a 200 MB file to make sure we have the room needed later
        dd if=/dev/urandom oflag=direct of=balloon.dat bs=1024k count=200
        rm -f balloon.dat
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: Server Integration Tests
      run: |
        export WORKSPACE=${GITHUB_WORKSPACE}
        build/db2-migration-test-docker.sh
        mvn -B test -DskipTests=false -f fhir-server-test --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
        build/post-integration-test-docker.sh
    - name: Gather error logs
      if: failure()
      run: |
        it_results=integration-test-results
        rm -fr ${it_results} 2>/dev/null
        mkdir -p ${it_results}/server-logs
        mkdir -p ${it_results}/fhir-server-test
        containerId=$(docker ps -a | grep fhir | cut -d ' ' -f 1)
        if [[ -z "${containerId}" ]]; then
            echo "Warning: Could not find fhir container!!!"
        else
            echo "fhir container id: $containerId"

            # Grab the container's console log
            docker logs $containerId  >& ${it_results}/docker-console.txt

            echo "Gathering post-test server logs from docker container: $containerId"
            docker cp -L $containerId:/logs ${it_results}/server-logs
        fi
        echo "Gathering integration test output"
        cp -pr ${GITHUB_WORKSPACE}/fhir-server-test/target/surefire-reports/* ${it_results}/fhir-server-test || true
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: db2-migration-test-results-${{ matrix.java }}
        path: integration-test-results
