name: Javadocs Build for Site

on:
  push:
    tags:
        - '*'
  # allows the workflow to be manually executed any time
  workflow_dispatch:

permissions:
  pages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11']
      fail-fast: false
    steps:
    - name: Gets the version
      id: get_version
      run: echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Setup GraphViz environment for PlanetUML/JavaDoc Graphics
      uses: ts-graphviz/setup-graphviz@v1
    - name: Grab the main Branch
      uses: actions/checkout@v2.3.3
      with:
            ref: refs/heads/main
            fetch-depth: 1
            path: fhir
            token: ${{ secrets.GITHUB_TOKEN }}
    - name: Grab the GH-Pages Branch
      uses: actions/checkout@v2.3.3
      with:
            ref: refs/heads/gh-pages
            fetch-depth: 1
            path: gh-pages
            token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build fhir-examples
      run: |
            cd fhir
            mvn -B -ntp clean install --file fhir-examples -Dversion.release=${TAG_VERSION} -Dmaven.wagon.http.retryHandler.count=3
            mvn -ntp -B -N -Pset-version-release clean -f fhir-examples -Dversion.release=${TAG_VERSION} -Dmaven.wagon.http.retryHandler.count=3
            mvn -ntp -B install --file fhir-examples -DskipTests -Dversion.release=${TAG_VERSION} -Dmaven.wagon.http.retryHandler.count=3
    - name: Build fhir-parent without tests
      run: |
            cd fhir
            export OLD_JAVA_HOME=/opt/hostedtoolcache/AdoptOpenJDK/1.0.0-ga-11-jdk-hotspot-linux-x64-normal-latest/x64/
            mvn -ntp -B -N -Pset-version-release clean -f fhir-parent -Ddeploy.version=${TAG_VERSION} -Dfhir-tools.version=${TAG_VERSION} -Dmaven.wagon.http.retryHandler.count=3
            mvn -ntp -DskipTests -B clean install org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc-no-fork org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:test-javadoc-no-fork org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:aggregate -f fhir-parent  -Ddeploy.version=${TAG_VERSION} -Dfhir-tools.version=${TAG_VERSION}  -Dmaven.wagon.http.retryHandler.count=3
            cp -R fhir-parent/target/site/apidocs ../apidocs/
    - name: Commit and Add GH-Pages
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CI: true
      run: |
            cd gh-pages
            echo "Working Directory is $(pwd)"
            if [ -d './javadocs/latest/' ]
            then
              rm -rf ./javadocs/latest/
            fi
            # Helps debug the situation
            ls -al javadocs
            echo "Starting the movement of the data around"
            mkdir -p javadocs/latest
            mv -f ../apidocs/* javadocs/latest/
            cp -Rf javadocs/latest javadocs/${TAG_VERSION}
            date > build.txt
            echo "[javadocs]" >> build.txt

            # Regenerate the index.html for javadocs/index.html
            echo "<html><title>Javadocs</title><body>" > javadocs/index.html
            for DIR in `find ./javadocs -type d -maxdepth 1 -mindepth 1 -exec basename {} \; | sort -r | grep -v rc3 `
            do
              echo "<a href=\"https://linuxforhealth.github.io/FHIR/javadocs/${DIR}/index.html?overview-summary.html\">${DIR}</a>" >> javadocs/index.html
              echo "<br>" >> javadocs/index.html
            done
            echo "</body></html>" >> javadocs/index.html

            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global user.name "Github Actions Bot - GH-Pages"
            git add .
            git commit -m "Automated gh-pages deployment of javadocs: $(date -u)"
    - name: Push changes to GH Pages
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CI: true
      run: |
            echo "Pushing Changes to gh-pages"
            cd gh-pages
            git branch
            remote_repo="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push "${remote_repo}" HEAD:gh-pages
