name: Reindex - Integration Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'demo/**'
      - '.github/workflows/site.yml'
      - '.github/workflows/release.yml'

jobs:
  reindex:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        datastore: [ 'derby', 'postgres' ]
      fail-fast: false
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2.3.4
    - name: Set up java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Setup prerequisites
      env:
        WORKSPACE: ${{ github.workspace }}
      run: bash build/reindex/bin/setup-prerequisites.sh ${{matrix.datastore}}
    - name: Integration Tests
      env:
        WORKSPACE: ${{ github.workspace }}
      run: |
        bash build/reindex/bin/pre-integration-test.sh ${{matrix.datastore}}
        bash build/reindex/bin/integration-test.sh ${{matrix.datastore}}
        bash build/reindex/bin/post-integration-test.sh ${{matrix.datastore}}
    - name: Gather error logs
      if: failure()
      env:
        WORKSPACE: ${{ github.workspace }}
      run: bash build/common/gather-posttest-logs.sh reindex ${{matrix.datastore}}
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: integration-test-results-${{ matrix.datastore }}
        path: build/reindex/integration-test-results

concurrency:
  group: reindex-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true