name: Build and Release

on:
  push:
    tags:
      - '*.*'
    paths-ignore:
    - 'docs/**'
    - 'demo/**'
    - '.github/workflows/site.yml'
    - '.github/workflows/javadocs.yml'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
      fail-fast: false
    steps:
    - name: Checkout the Main Branch
      uses: actions/checkout@v2.3.3
      with:
        ref: refs/heads/main
        fetch-depth: 1
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Release
      env:
        BASE: origin/${{ github['base_ref'] }}
        GITHUB_TOKEN: ${{ secrets.DOCS_SITE_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        GPG_KEY_FILE: ${{ secrets.GPG_KEY_FILE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OLD_JAVA_HOME: /opt/hostedtoolcache/AdoptOpenJDK/1.0.0-ga-11-jdk-hotspot-linux-x64-normal-latest/x64/
      run: |
        . build/release/global.sh
        bash build/release/00_prep.sh
        bash build/release/10_build.sh
        bash build/release/20_test.sh
        bash build/release/30_release.sh
        bash build/release/40_drop.sh
    - name: Gather artifacts and materials
      if: always()
      run: |
        bash build/release/50_gather.sh
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v2.2.3
      with:
        name: release-tag
        path: |
          build/release/workarea/release_files
        if-no-files-found: ignore
