name: Application Security Testing

# The workflow creates the build/release artifacts and runs a set of workflow configured tests.
# See build/security/README.md for more details.

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'demo/**'
      - '.github/**'
  schedule:
    # Runs on Saturday
    - cron: '1 1 * * 6'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    # Check to see if it's scheduled or has a security label
    if: "contains(github.event.pull_request.labels.*.name, 'security') || contains(github.event.schedule, '1 1 * * 6') "
    strategy:
      matrix:
        java: [ '11' ]
      fail-fast: false
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2.3.3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Setup prerequisites
      run: |
        export WORKSPACE=${GITHUB_WORKSPACE}
        bash build/security/setup.sh
    - name: Security
      env:
        SCANNERS: 'asoc'
        APPSCAN_SECRET: ${{ secrets.APPSCAN_SECRET }}
        APPSCAN_KEY: ${{ secrets.APPSCAN_KEY }}
        APPSCAN_APPID: ${{ secrets.APPSCAN_APPID }}
      run: |
        export WORKSPACE=${GITHUB_WORKSPACE}
        bash build/security/run.sh
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: security-testing-results
        path: build/security/logs/output
