name: Integration - Windows

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'demo/**'
      - '.github/workflows/site.yml'

jobs:
  e2e-windows:
    runs-on: windows-2019
    if: "!contains(github.event.pull_request.labels.*.name, 'ci-skip')"
    strategy:
      matrix:
        java: [ '11' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Setup java
      uses: actions/setup-java@v2.3.1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 8GB
        maximum-size: 8GB
        disk-root: "C:"
    - name: Build tools and samples
      shell: powershell
      run: |
        mvn -B install --file fhir-tools --no-transfer-progress
        mvn -B install --file fhir-examples --no-transfer-progress
    - name: Download Dependencies
      shell: powershell
      run: mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline -f fhir-parent -DexcludeReactor=true
    - name: Download Plugins
      shell: powershell
      run: mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:resolve-plugins -f fhir-parent -DexcludeReactor=true
    - name: Build parent without tests
      shell: powershell
      run: mvn -B install --file fhir-parent -P include-fhir-igs,condense-json --no-transfer-progress
    - name: Server Integration Tests
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"
        & build/pre-integration-test.ps1
        & build/tests.ps1
        & build/post-integration-test.ps1
    - name: Gather error logs
      shell: powershell
      if: failure()
      run: |
        Write-Host 'Clean up existing integration test results'
        $it_results='SIT/integration-test-results'
        If (Test-Path -Path $it_results) {
          Remove-Item -path $it_results -Recurse -Force
        }

        Write-Host 'Create destinations for the files/folders'
        $DST_SL='server-logs'
        $DST_ST='fhir-server-test'
        New-Item -Path $it_results -Name $DST_SL -ItemType 'directory' -Force
        New-Item -Path $it_results -Name $DST_ST -ItemType 'directory' -Force

        Write-Host 'Gathering post-test server logs'
        $SRC_ST='SIT/wlp/usr/servers/defaultServer/logs'
        $DST_SL_F=$it_results + '/' + $DST_SL
        Copy-Item -Path $SRC_ST -Destination $DST_SL_F -Recurse -Force -ErrorAction SilentlyContinue

        Write-Host 'Gathering integration test output'
        $SRC_ST='./fhir-server-test/target/surefire-reports'
        $DST_ST_F=$it_results + '/' + $DST_ST
        Copy-Item -Path $SRC_ST -Destination $DST_ST_F -Recurse -Force -ErrorAction SilentlyContinue

        Copy-Item -Path stdout.txt -Destination $DST_ST_F -Force -ErrorAction SilentlyContinue
        Copy-Item -Path stderr.txt -Destination $DST_ST_F -Force -ErrorAction SilentlyContinue
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: integration-test-results-windows-${{ matrix.java }}
        path: SIT/integration-test-results

concurrency:
  group: windows-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true